
222
homeassistant:
  # Name of the location where Home Assistant is running
  # 智能家居系统的名字，显示在主界面顶部。
  name: 我的智能豪宅
  # Location required to calculate the time the sun rises and sets
  # 下面填入纬度和经度，计算太阳升起和设定时间所需位置，越精确越好。
  latitude: 36.85201
  longitude: 116.225287
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # 海拔高度用于修正天气参数和日出日落时间参数 (默认单位是：米)。
  elevation: 31
  # metric for Metric, imperial for Imperial
  # 度量衡单位制式（metric）是公制，（imperial）是英制。
  unit_system: metric
  # Pick yours from here: [url]http://en.wikipedia.org/wiki/List_of_tz_database_time_zones[/url]
  # 时区，从这里选择你的：[url]http://en.wikipedia.org/wiki/List_of_tz_database_time_zones[/url]，默认北京时间。
  time_zone: Asia/Shanghai
  customize: !include customize.yaml
 
# 测试任何您更改的配置文件，在命令行中用hass --script check_config。这个脚本可以让你测试的变化而不需要重新启动家庭助理。
# Show links to resources in log and frontend
# 在网页界面的首页显示简介  （那一大段英文）不想看到的话，请在前面加上#号。
#introduction:
 
# Enables the frontend
# 是否使用默认的“首页”
frontend:
 
# Enables configuration UI
# 自定义配置UI
config:
 
http:
  # Uncomment this to add a password (recommended!)
  # 给系统网页的登录加上一个密码，先去掉下面这行的#号，然后把PASSWORD改成你想要的密码。
  # api_password:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
 
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# [url]https://home-assistant.io/blog/2016/10/25/explaining-the-updater/[/url]
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # 升级提示，当 HomeAssitant 有新版本发布的时候，“日出日落”图标会变成（Updater）字样
  # include_used_components: true
 
# Discover some devices automatically
# 系统自动发现新的设备
discovery:
 
# Allows you to issue voice commands from the frontend in enabled browsers
# 启动浏览器的语音命令
conversation:
 
# Enables support for tracking state changes over time
# 在系统数据库中保存“历史数据”
history:
 
# View all events in a logbook
# 在logbook显示所有事件
logbook:
 
# receive from broadlink开启博联日志
logger:
  default: critical
  logs:
    homeassistant.components.switch.broadlink: info
 
# Track the sun
# 太阳“跟踪器”    也就是“日出日落时间”
#sun:
 
panel_iframe:
#添加HA侧边面板
  designicons:
    title: 'Design Icons'
    icon: mdi:vector-square
    url: 'https://cdn.materialdesignicons.com/2.0.46/'
 
 
 
 
 
# Text to speech
# 文字转换语音
tts:
  - platform: google
 
# 播放器
media_player:
#  - platform:
#    host:
 
 
device_tracker:
  - platform: xiaomi
    host: 192.168.31.1
    username: admin
    password: '**************'#这个不用我说了吧，换成自己的
    track_new_devices : 1
    #If new discovered devices are tracked by default
    #跟踪新设备的添加，默认true
    interval_seconds : 12
    #Seconds between each scan for new devices
    #扫描每个设备的间隔
    consider_home : 180
    #Seconds to wait till marking someone as not home after not being seen.
    #This parameter is most useful for households with Apple iOS devices that go into sleep mode while still at home to conserve battery life.
    #iPhones will occasionally drop off the network and then re-appear.
    #It helps prevent false alarms in presence detection when using IP scanners such as Nmap.
    #Accepts various time representations, (E.g. the following all represents 3 minutes:180,0:03,0:03:00）
    #在设定秒数之后追踪不到某个设备，设置为不在家
    #这个参数对于那些在家时进入睡眠模式的苹果iOS设备非常有用，以节省电池寿命。
    #iPhone偶尔会脱离网络，然后重新出现。在使用IP扫描器如Nmap进行检测时有助于防止误报。
    #接受各种时间表示（例如，以下代表3分钟：180,0：03,0：03：00）
 
 
# 下面这个区域，用于自定义设备属性
 
switch: !include switchs.yaml
group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml